name: "Deployment Lite"

on:
  push:
    branches:
      - master
    paths:
      - "lite/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    defaults:
      run:
        working-directory: lite
    steps:
    - uses: actions/checkout@v1
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@master
      env:
        VERSION: ${{ env.GITHUB_SHA }}
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.ORG_ID }}
        vercel-project-id: prj_ewqxzoebkqkG7yUcdJIDQTG07LQ7
        working-directory: ./
        vercel-args: '--prod'
